### ISSUE TITLE
trial_terms_of_use_url, 404 error

### ISSUE THREAD

**Issue by ckizer** [techvalidate/pano#57]
trial_terms_of_use_url results in a 404 error.

**Reproduce by visiting:**
https://cx.surveymonkey.com/signup

**click the link on the page**
SurveyMonkey Trial Account Terms of Service

It should be reverted to wherever the link originally pointed before the 404 error. 
Alternatively if trial_terms_of_use_url was always incorrect you could use: 
https://www.surveymonkey.com/mp/policy/surveymonkey-trial-account-terms-service/

**Comment by jonwolfe** [comment]
umm, so you need to tell us what the right free trial terms of use url is

**Comment by jmckible** [comment]
Assigning to @ckizer awaiting correct url.

**Comment by ckizer** [comment]
I found the broken link by browsing to https://cx.surveymonkey.com/signup and clicking "SurveyMonkey Trial Account Terms of Service". It should be reverted to wherever the link original pointed to before the 404 error. Alternatively if trial_terms_of_use_url was always broken you could use: 
https://en.surveymonkey.com/mp/policy/terms-of-use/

**Comment by jonwolfe** [comment]
hey @mkmiller, [this commit](https://github.com/techvalidate/pano/commit/c1c446f89809fd39012e2c6bc8de304b97f3c7db) either broke the free trial terms of use link, or else they moved the page after the fact.

It looks like the url works with www as the subdomain: https://www.surveymonkey.com/mp/policy/surveymonkey-trial-account-terms-service/

Maybe they never made this particular page work with the cctlds, or it subsequently broke.

@ckizer there is a different terms of use for the free trial that we were told to use

**Comment by mkmiller** [comment]
@jonwolfe SM broke the links. I'll ask Michele
